// you need to add them all
// http://www.w3schools.com/js/js_reserved.asp
var javascript_keywords = {
  "lineComment":{
    "type":{
      "start":"//"
    }
  },
  "comment":{
    "type":{
      "start":"/*",
      "end":"*/"
    }
  },
  "string-1":{
    "type":{
      "startEnd":"'"
    }
  },
  "string-2":{
    "type":{
      "startEnd":'"'
    }
  },
  "keyword-1":{
    "type":{
      "start":"function"          
    }
  },
  "keyword-2":{
    "type":{
      "start":"var"
    }
  },        
  "keyword-3":{
    "type":{
      "start":"void"
    }
  }
}